#!/usr/bin/env ruby

require './file_helper'

if ARGV.length != 1
  puts "Argument error!"
  puts "Usage: advent 20-01-1 (2020 first day part 1)"
  exit
end

year, day, part = ARGV.first.split('-')
base_path = "./20#{year}/#{day}"
code_path = [base_path, "part#{part}"].join("/")
data_path = [base_path, "data.txt"].join("/")

@data = File.exist?(data_path) ? FileHelper.new(data_path) : nil

require code_path
